LaptopRehab: documenting current progress and added SMART HDD check

diff --git a/src/usbboot/install-ubuntu b/src/usbboot/install-ubuntu
--- a/src/usbboot/install-ubuntu
+++ b/src/usbboot/install-ubuntu
@@ -80,6 +80,17 @@ testcpu() {
     fi
 }
 
+testsmart() {
+    echo "${WHITE}Gathering SMART data on HDD ${BLUE}${HDD}${WHITE}.${NORMAL}"
+
+    smartctl -H "/dev/${HDD}"
+    smartstat="$(($? & 220))"
+
+    if [ $smartstat -gt 0 ]; then
+        error "${RED}HDD ${BLUE}/dev/${HDD}${RED} appears to be failing or had recent errors.${NORMAL}"
+    fi
+}
+
 usbmount() {
     USBDEVICE="$(blkid -L 'CMU Laptop Rehab 32-bit' | grep 's[d|r][^0-9]*' -o)"
     USBPART="$(blkid -L 'CMU Laptop Rehab 32-bit')"
@@ -156,6 +167,7 @@ testcpu
 
 usbmount
 findhdd
+testsmart
 copyubuntu
 resizepart
 
