usbboot/install-ubuntu: gracefully handle errors at anypoint

diff --git a/src/usbboot/install-ubuntu b/src/usbboot/install-ubuntu
--- a/src/usbboot/install-ubuntu
+++ b/src/usbboot/install-ubuntu
@@ -33,14 +33,43 @@
 
 export PATH=/usr/local/sbin:/usr/local/bin:"$PATH"
 
+# Dealing with errors
+ERROR_MKDIR="Could not create mount directory."
+ERROR_MOUNT="Could not mount USB partition."
+ERROR_DECOMPRESS="Failed while writing to the HDD."
+ERROR_MKSWAP="Failed creating swap partition."
+ERROR_RESIZE2="Failed resizing partition 2."
+ERROR_RESIZE5="Failed resizing partition 5."
+ERROR_SYNC="Failed sync'ing to HDD."
+ERROR_PARTX="Could not re-read and update partition table."
+ERROR_FSCK="Failed file system check."
+ERROR_RESIZE="Failed file system resize."
+
+error() {
+    message="$1"
+    echo "${RED}Error: ${message}${NORMAL}"
+    echo "${RED}Press any key to continue to a debug shell.${NORMAL}"
+    echo "${RED}If you do not know what to do when the shell appears, just type '${BLUE}poweroff${NORMAL}' and hit '${WHITE}Enter${NORMAL}'.${NORMAL}"
+    read junk
+    exit 1
+}
+
+testret() {
+    if [ $1 -ne 0 ]; then
+        error "$2"
+    fi
+}
 usbmount() {
     USBDEVICE="$(blkid -L 'CMU Laptop Rehab 32-bit' | grep sd[^0-9]* -o)"
     USBPART="$(blkid -L 'CMU Laptop Rehab 32-bit')"
     echo "${WHITE}Found USB partition at: ${BLUE}${USBPART}.${NORMAL}"
     if [ ! -e /mnt/$(basename ${USBPART}) ]; then
         mkdir -p /mnt/$(basename ${USBPART})
+        testret $? "${ERROR_MKDIR}"
     fi
+
     mount "${USBPART}" /mnt/$(basename ${USBPART})
+    testret $? '"${ERROR_MOUNT}"'
 
     USBMOUNT="/mnt/$(basename ${USBPART})"
     echo "${WHITE}USB partition should be mounted at: ${BLUE}${USBMOUNT}.${NORMAL}"
@@ -53,26 +82,48 @@ findhdd() {
 
 copyubuntu() {
     echo "${WHITE}Decompressing OS image to HDD."
+
     gunzip -c "${USBMOUNT}/Ubuntu32.img.gz" | pv -s 6656m -p -t -e -r -B 512k > "/dev/${HDD}"
+    testret $? "${ERROR_DECOMPRESS}"
+
     sync
+    testret $? "${ERROR_SYNC}"
 }
 
 fixswap() {
     echo "${WHITE}Creating swap space.${NORMAL}"
+
     mkswap "/dev/${HDD}1"
+    testret $? "${ERROR_MKSWAP}"
 }
 
 resizepart() {
     echo "${WHITE}Resizing partition.${NORMAL}"
+
     parted -s "/dev/${HDD}" resizepart 2 100%
+    testret $? "${ERROR_RESIZE2}"
+
     parted -s "/dev/${HDD}" resizepart 5 100%
+    testret $? "${ERROR_RESIZE5}"
+
     echo "${WHITE}Resizing file system.${NORMAL}"
     sync
+    testret $? "${ERROR_SYNC}"
+
     partx -u "/dev/${HDD}"
+    testret $? "${ERROR_PARTX}"
+
     e2fsck -f "/dev/${HDD}5"
+    testret $? "${ERROR_FSCK}"
+
     sync
+    testret $? "${ERROR_SYNC}"
+
     resize2fs "/dev/${HDD}5"
+    testret $? "${ERROR_RESIZE}"
+
     sync
+    testret $? "${ERROR_SYNC}"
 }
 
 waitfstab() {
